nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['']
        max_age: 0
        hosts: []
        forced_allow_origin_value: ~
    paths:
        
         '^/api/':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
        #  '^/':
        #         origin_regex: true
        #         allow_origin: ['*']
        #         #allow_origin: ['^http://localhost:[0-9]+']
        #         allow_headers: ['Content-Type', 'Authorization']
        #         #allow_headers: ['X-Custom-Auth']
        #         allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        #         max_age: 3600
        #         hosts: ['^api\.']
         '^/': ~